In [1]:
import numpy as np
import pandas as pd

In [2]:
charts_raw = pd.read_csv("../data/eu_charts.csv")
charts = charts_raw.copy()
charts.info()

<class 'pandas.DataFrame'>
RangeIndex: 8738193 entries, 0 to 8738192
Data columns (total 9 columns):
 #   Column   Dtype
---  ------   -----
 0   title    str
 1   rank     int64
 2   date     str
 3   artist   str
 4   url      str
 5   region   str
 6   chart    str
 7   trend    str
 8   streams  float64
dtypes: float64(1), int64(1), str(7)
memory usage: 600.0 MB

In [3]:
# We want to merge 2 or more datasets, so we need a common key. 
# The "url" column contains Spotify track URLs, which include the track ID. 
# We can extract the track ID from the URL to create a new "track_id" column 
# that will serve as a common key for merging with the tracks dataset.
charts['url'].isna().sum()

np.int64(0)

In [4]:
# Example url: https://open.spotify.com/track/2ZywW3VyVx6rrrrX75n3JB?si=xxxx
charts["track_id"] = (
    charts["url"]
      .str.split("/track/", n=1).str[-1]   # keep part after "/track/"
      .str.split("?", n=1).str[0]          # remove query params
      .str.strip()
)

charts.drop(columns=['artist','url','trend'], inplace=True)

In [5]:
tracks_raw = pd.read_csv("../data/kaggle2/tracks.csv")
tracks = tracks_raw.copy()
tracks.info()

<class 'pandas.DataFrame'>
RangeIndex: 586672 entries, 0 to 586671
Data columns (total 20 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                586672 non-null  str
 1   name              586601 non-null  str
 2   popularity        586672 non-null  int64
 3   duration_ms       586672 non-null  int64
 4   explicit          586672 non-null  int64
 5   artists           586672 non-null  str
 6   id_artists        586672 non-null  str
 7   release_date      586672 non-null  str
 8   danceability      586672 non-null  float64
 9   energy            586672 non-null  float64
 10  key               586672 non-null  int64
 11  loudness          586672 non-null  float64
 12  mode              586672 non-null  int64
 13  speechiness       586672 non-null  float64
 14  acousticness      586672 non-null  float64
 15  instrumentalness  586672 non-null  float64
 16  liveness          586672 non-null  float64
 17  valence           586672 non-null  float64
 18  tempo             586672 non-null  float64
 19  time_signature    586672 non-null  int64
dtypes: float64(9), int64(6), str(5)
memory usage: 89.5 MB

In [6]:
tracks = tracks.rename(columns={"id": "track_id"})

In [7]:
artists_raw = pd.read_csv("../data/kaggle2/artists.csv")
artists = artists_raw.copy()
artists.info()

<class 'pandas.DataFrame'>
RangeIndex: 1162095 entries, 0 to 1162094
Data columns (total 5 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   id          1162095 non-null  str
 1   followers   1162084 non-null  float64
 2   genres      1162095 non-null  str
 3   name        1162092 non-null  str
 4   popularity  1162095 non-null  int64
dtypes: float64(1), int64(1), str(3)
memory usage: 44.3 MB

In [8]:
merged_df = charts.merge(tracks, on="track_id", how="left")
merged_df

,title,rank,date,region,chart,streams,track_id,name,popularity,duration_ms,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
0,Alone,1,2017-01-01,Austria,top200,12990.0,0JiVRyTJcJnmlwCZ854K4p,Alone,66.0,161200.0,...,10.0,-3.194,1.0,0.0458,0.1860,0.000405,0.1210,0.157,97.019,4.0
1,Rockabye (feat. Sean Paul & Anne-Marie),2,2017-01-01,Austria,top200,12897.0,5knuzwU65gJK7IF5yJsuaW,Rockabye (feat. Sean Paul & Anne-Marie),78.0,251088.0,...,9.0,-4.068,0.0,0.0523,0.4060,0.000000,0.1800,0.742,101.965,4.0
2,Chöre,3,2017-01-01,Austria,top200,10852.0,2nYpbaLykC2cjU8Yt5KF1v,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Bad Ideas,4,2017-01-01,Austria,top200,10837.0,76gwG061wqdatYhicO2hG4,Bad Ideas,57.0,166213.0,...,7.0,-6.630,1.0,0.0331,0.0163,0.023700,0.0892,0.678,120.005,4.0
4,Closer,5,2017-01-01,Austria,top200,10317.0,7BKLCZ1jbUBVqRi2FVlTVw,Closer,86.0,244960.0,...,8.0,-5.599,1.0,0.0338,0.4140,0.000000,0.1110,0.661,95.010,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8738188,RUTHLESS,46,2021-07-31,Sweden,viral50,NaN,5U2oQrjYu3VqQoH5OAyyxq,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8738189,Blomstertid,47,2021-07-31,Sweden,viral50,NaN,31gGBW3iiuwtrLwiJYLROq,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8738190,Je te laisserai des mots,48,2021-07-31,Sweden,viral50,NaN,0V5cvmTKsYmF5FmGGEAfmS,Je te laisserai des mots,72.0,160853.0,...,2.0,-16.757,1.0,0.0356,0.9890,0.489000,0.1010,0.213,132.731,4.0
8738191,Tiroteo - Remix,49,2021-07-31,Sweden,viral50,NaN,4OwhwvKESFtuu06dTgct7i,Tiroteo - Remix,64.0,321556.0,...,9.0,-7.018,1.0,0.0293,0.2820,0.000000,0.0743,0.601,110.427,4.0
8738192,Like My Father,50,2021-07-31,Sweden,viral50,NaN,5YVmHTAsdWnoanWXB7AwZX,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# Check missing values in "tempo" column by region
merged_df.groupby('region')['tempo'].apply(lambda x: x.isna().sum() / len(x))

region
Austria           0.417637
Belgium           0.364035
Bulgaria          0.337243
Czech Republic    0.333135
Denmark           0.374814
Estonia           0.353934
Finland           0.398675
France            0.459292
Germany           0.456878
Greece            0.307147
Hungary           0.313755
Ireland           0.333693
Italy             0.409207
Latvia            0.341821
Lithuania         0.349113
Luxembourg        0.389718
Netherlands       0.440161
Poland            0.394689
Portugal          0.325236
Romania           0.264435
Slovakia          0.345076
Spain             0.367621
Sweden            0.428306
Name: tempo, dtype: float64

⚠️ There are too many missing audio features in the merged dataset. 
So instead of a left join (more accurate analysis) we'll switch to a inner join instead.
We could consider augmenting the dataset using: https://www.kaggle.com/datasets/maharshipandya/-spotify-tracks-dataset

In [10]:
inner_merged_df = charts.merge(tracks, on="track_id", how="inner")
inner_merged_df

,title,rank,date,region,chart,streams,track_id,name,popularity,duration_ms,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
0,Alone,1,2017-01-01,Austria,top200,12990.0,0JiVRyTJcJnmlwCZ854K4p,Alone,66,161200,...,10,-3.194,1,0.0458,0.18600,0.000405,0.1210,0.157,97.019,4
1,Rockabye (feat. Sean Paul & Anne-Marie),2,2017-01-01,Austria,top200,12897.0,5knuzwU65gJK7IF5yJsuaW,Rockabye (feat. Sean Paul & Anne-Marie),78,251088,...,9,-4.068,0,0.0523,0.40600,0.000000,0.1800,0.742,101.965,4
2,Bad Ideas,4,2017-01-01,Austria,top200,10837.0,76gwG061wqdatYhicO2hG4,Bad Ideas,57,166213,...,7,-6.630,1,0.0331,0.01630,0.023700,0.0892,0.678,120.005,4
3,Closer,5,2017-01-01,Austria,top200,10317.0,7BKLCZ1jbUBVqRi2FVlTVw,Closer,86,244960,...,8,-5.599,1,0.0338,0.41400,0.000000,0.1110,0.661,95.010,4
4,Call On Me - Ryan Riback Extended Remix,8,2017-01-01,Austria,top200,9146.0,78rIJddV4X0HkNAInEcYde,Call On Me - Ryan Riback Extended Remix,50,222041,...,0,-4.031,1,0.0362,0.06040,0.000611,0.1590,0.717,104.998,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5468932,Beggin',20,2021-07-31,Sweden,viral50,NaN,3Wrjm47oTz2sjIgck11l5e,Beggin',59,211560,...,11,-4.808,0,0.0504,0.12700,0.000000,0.3590,0.589,134.002,4
5468933,Ramenez la coupe à la maison,28,2021-07-31,Sweden,viral50,NaN,1m0UFnuTktOkksvjbF9z0m,Ramenez la coupe à la maison,73,235556,...,0,-6.237,0,0.0395,0.03580,0.000000,0.1380,0.804,107.992,4
5468934,I WANNA BE YOUR SLAVE,40,2021-07-31,Sweden,viral50,NaN,4pt5fDVTg5GhEvEtlz9dKk,I WANNA BE YOUR SLAVE,67,173347,...,1,-4.008,1,0.0387,0.00165,0.000000,0.1780,0.958,132.507,4
5468935,Je te laisserai des mots,48,2021-07-31,Sweden,viral50,NaN,0V5cvmTKsYmF5FmGGEAfmS,Je te laisserai des mots,72,160853,...,2,-16.757,1,0.0356,0.98900,0.489000,0.1010,0.213,132.731,4
5468936,Tiroteo - Remix,49,2021-07-31,Sweden,viral50,NaN,4OwhwvKESFtuu06dTgct7i,Tiroteo - Remix,64,321556,...,9,-7.018,1,0.0293,0.28200,0.000000,0.0743,0.601,110.427,4

In [11]:
inner_merged_df.groupby('region')['valence'].apply(lambda x: x.isna().sum() / len(x))

region
Austria           0.0
Belgium           0.0
Bulgaria          0.0
Czech Republic    0.0
Denmark           0.0
Estonia           0.0
Finland           0.0
France            0.0
Germany           0.0
Greece            0.0
Hungary           0.0
Ireland           0.0
Italy             0.0
Latvia            0.0
Lithuania         0.0
Luxembourg        0.0
Netherlands       0.0
Poland            0.0
Portugal          0.0
Romania           0.0
Slovakia          0.0
Spain             0.0
Sweden            0.0
Name: valence, dtype: float64

In [27]:
inner_merged_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5468937 entries, 0 to 5468936
Data columns (total 25 columns):
 #   Column            Dtype
---  ------            -----
 0   title             str
 1   rank              int64
 2   date              datetime64[us]
 3   region            str
 4   chart             str
 5   streams           float64
 6   track_id          object
 7   popularity        int64
 8   duration_ms       int64
 9   explicit          int64
 10  artists           str
 11  id_artists        str
 12  release_date      str
 13  danceability      float64
 14  energy            float64
 15  key               int64
 16  loudness          float64
 17  mode              int64
 18  speechiness       float64
 19  acousticness      float64
 20  instrumentalness  float64
 21  liveness          float64
 22  valence           float64
 23  tempo             float64
 24  time_signature    int64
dtypes: datetime64[us](1), float64(10), int64(7), object(1), str(6)
memory usage: 1.0+ GB

In [ ]:
# Convert date column from string to date format
inner_merged_df['date'] = pd.to_datetime(inner_merged_df['date'])
# title and name are duplicates, drop the name column
inner_merged_df.drop(columns = 'name', inplace = True)

In [28]:
inner_merged_df.to_csv("../data/eu_charts_with_tracks_data.csv", index=False)